# .github/workflows/deploy-pages.yml
name: Deploy Sandbox to GitHub Pages

on:
  push:
    branches: [master] # adjust if you deploy from main
  workflow_dispatch: # allow manual trigger

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - uses: actions/checkout@v4

      # 2. Setup pnpm and Node.js
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9 # You can specify a version, or it will use the one from package.json

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "pnpm"

      # 3. Install workspace deps
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # 4. Build the sandbox AND its dependencies
      - name: Build
        run: pnpm --filter 'sandbox...' build

      # 5. Setup Pages
      - uses: actions/configure-pages@v4

      # 6. Upload build artifact
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: packages/sandbox/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
